name = "PauliPropagation"
uuid = "293282d5-3c99-4fb6-92d0-fd3280a19750"
version = "0.5.2"
authors = ["Manuel S. Rudolph"]

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
BitIntegers = "c3b6d118-76ef-56ca-8cc7-ebb389d030a1"
Bits = "1654ce90-6ed3-553a-957f-9452c3a40996"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PlotGraphviz = "78a92bc3-407c-4e2f-aae5-75bb47a6fe36"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
BenchmarkTools = "1.6.3"
BitIntegers = "0.3"
Bits = "0.2"
Combinatorics = "1.0.3"
DataStructures = "0.19.3"
Graphs = "1.13.2"
IterTools = "1.10.0"
JSON = "0.21.4"
OrderedCollections = "1.8.1"
PlotGraphviz = "0.6.3"
Plots = "1.41.1"
PyCall = "1.96.4"
PyPlot = "2.11.6"
StatsBase = "0.34"
Test = "1.10"
UUIDs = "1.10"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Yao = "5872b779-8223-5990-8dd0-5abbb0748c8c"

[targets]
test = ["Yao", "Test"]
